name: 'Verify Trello URL in PR'
description: 'Action to verify that there is at least one Trello URL in the PR description'
inputs:
  pr-description:
    description: 'description of pull request input'
    required: true
  trello-api-key:
    description: 'trello api key'
    required: true
  trello-api-token:
    description: 'trello api key'
    required: true
outputs:
  is-included: # bool
    description: 'Boolean: Is there a Trello URL and is it found on Trello.com?'
runs:
  using: 'node16'
  main: 'index.js'